'use strict';
// tests for access
// Generated by serverless-mocha-plugin

const mod         = require('../handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-access'
}

describe('access', () => {
  before(function (done) {
//  wrapper.init(liveFunction); // Run the deployed lambda 
    wrapper.init(mod, {
      handler: 'access'
    });

    done()
  })
  
  it('implement tests here', (done) => {
    wrapper.run({body: {code: 'test'}}, (err, response) => {
      expect(response).to.include.keys('ok');
      done();
    });
  });
});