'use strict';
// tests for challenge
// Generated by serverless-mocha-plugin

const mod         = require('../handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-challenge'
}

describe('challenge', () => {
  before(function (done) {
//  wrapper.init(liveFunction); // Run the deployed lambda 
    wrapper.init(mod, {
      handler: 'challenge'
    });

    done()
  })
  
  it('implement tests here', (done) => {
    wrapper.run({}, (err, response) => {
      done('no tests implemented');
    });
  });
});